dist: trusty

branches:
  only:
    - master

on:
  tags: true

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t alexa-story-time-api .
  - docker images
  - docker tag alexa-story-time-api $DOCKER_USERNAME/alexa-story-time-api
  - docker push $DOCKER_USERNAME/alexa-story-time-api



